app01/urls.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
# author:Administrator
# datetime:2020/1/4/004 9:26
# software: PyCharm

from django.contrib import admin
from django.urls import path,include,re_path
from . import views

app_name = 'myPerson'

urlpatterns = [
    # 查询 get
    path('', views.index, name='index'),
    path('getOne/<int:myPersonID>/', views.detail, name='detail'),
    # 新增 get + post
    path('add/', views.add, name='add'),
    # 删除 get
    path('delete/<int:myPersonID>/', views.delete, name='delete'),
    # 修改 get + post
    path('update/<int:myPersonID>/', views.update, name='update'),

]

app02/urls.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
# author:Administrator
# datetime:2020/1/4/004 9:26
# software: PyCharm

from django.contrib import admin
from django.urls import path,include,re_path
from . import views

app_name = 'app02'

urlpatterns = [
    # publisher
    path('publisherList/', views.publisher_list, name='publisherList' ),
    path('add_publisher/', views.add_publisher, name='publisherAdd'),
    path('delete_publisher', views.delete_publisher, name='publisherDelete'),
    path('edit_publisher', views.edit_publisher, name='publisherEdit'),
    # author
    path('authorList/', views.author_list, name='authorList' ),
    path('add_author/', views.add_author, name='authorAdd'),
    path('delete_author', views.delete_author, name='authorDelete'),
    path('edit_author', views.edit_author, name='authorEdit'),
]

myDjango00/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path,include,re_path
from django.conf import settings
from django.views import static
from django.conf.urls import url
from django.views.generic import TemplateView, RedirectView
from django.views.static import serve

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico')),
    # re_path(r'^media/(?P<path>.*)$', login_required(serve), kwargs={'document_root': settings.MEDIA_ROOT}),
    # re_path(r'^static/(?P<path>.*)$', login_required(serve), kwargs={'document_root': settings.STATIC_ROOT}, name='static'),
    # 注意login_required(serve)，日后需要权限控制
    re_path(r'^media/(?P<path>.*)$', static.serve, kwargs={'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', static.serve, kwargs={'document_root': settings.STATIC_ROOT},name='static'),
    # url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    # url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
    # path('media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
    # re_path('admin/|', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html")),
    path('admin/', admin.site.urls),
    path('app01/',include('app01.urls')),
    path('app02/',include('app02.urls')),
    path('app03/', include('app03.urls')),
    path('app04/', include('app04.urls')),
    path('app05/', include('app05.urls')),
    path('app06/', include('app06.urls')),

]

app02/models.py
from django.db import models


# Create your models here.

# 图书管理系统, 书  作者 出版社


# 出版社
class Publisher(models.Model):
    id = models.AutoField(primary_key=True)  # 自增的ID主键
    # 创建一个varchar(64)的唯一的不为空的字段
    name = models.CharField(max_length=64, null=False, unique=True)
    addr = models.CharField(max_length=128)

    def __str__(self):
        return "<Publisher Object: {}>".format(self.name)

    def publisher2dict(publisher):
        return {
            'id': publisher.name,
            'name': publisher.name,
            'addr': publisher.addr
        }

# 书
class Book(models.Model):
    id = models.AutoField(primary_key=True)  # 自增的ID主键
    # 创建一个varchar(64)的唯一的不为空的字段
    title = models.CharField(max_length=64, null=False, unique=True)
    # 和出版社关联的外键字段
    publisher = models.ForeignKey(to="Publisher", null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
            return "<Book Object: {}>".format(self.title)

# # 作者表
class Author(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=16, null=False, unique=True)
    # 告诉ORM 我这张表和book表是多对多的关联关系,ORM自动帮我生成了第三张表
    books = models.ManyToManyField(to="Book")

    def __str__(self):
        return "<Author Object: {}>".format(self.name)

app02/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from app02 import models

import time, logging, os
# Create your views here.

def publisher_list(request):
    # 去数据库查出所有的出版社,填充到HTML中,给用户返回
    ret = models.Publisher.objects.all().order_by("id")
    return render(request, "app02/publisher/publisher_list.html", {"publisher_list": ret})


# 添加新的出版社
def add_publisher(request):
    error_msg = ""
    # 如果是POST请求,我就取到用户填写的数据
    if request.method == "POST":
        new_name = request.POST.get("publisher_name", None)
        if new_name:
            # 通过ORM去数据库里新建一条记录
            models.Publisher.objects.create(name=new_name)
            # 引导用户访问出版社列表页,查看是否添加成功  --> 跳转
            return redirect("app02:publisherList")
        else:
            error_msg = "出版社名字不能为空!"
    # 用户第一次来,我给他返回一个用来填写的HTML页面
    return render(request, "app02/publisher/add_publisher.html", {"error": error_msg})


# 删除出版社的函数
def delete_publisher(request):
    print(request.GET)
    # 删除指定的数据
    # 1. 从GET请求的参数里面拿到将要删除的数据的ID值
    del_id = request.GET.get("id", None)  # 字典取值,娶不到默认为None
    # 如果能取到id值
    if del_id:
        # 去数据库删除当前id值的数据
        # 根据id值查找到数据
        del_obj = models.Publisher.objects.get(id=del_id)
        # 删除
        del_obj.delete()
        # 返回删除后的页面,跳转到出版社的列表页,查看删除是否成功
        return redirect("app02:publisherList")
    else:
        return HttpResponse("要删除的数据不存在!")


# 编辑出版社
def edit_publisher(request):
    # 用户修改完出版社的名字,点击提交按钮,给我发来新的出版社名字
    if request.method == "POST":
        print(request.POST)
        # 取新出版社名字
        edit_id = request.POST.get("id")
        new_name = request.POST.get("publisher_name")
        # 更新出版社
        # 根据id取到编辑的是哪个出版社
        edit_publisher = models.Publisher.objects.get(id=edit_id)
        edit_publisher.name = new_name
        edit_publisher.save()  # 把修改提交到数据库
        # 跳转出版社列表页,查看是否修改成功
        return redirect("app02:publisherList")
    # 从GET请求的URL中取到id参数
    edit_id = request.GET.get("id")
    if edit_id:
        # 获取到当前编辑的出版社对象
        publisher_obj = models.Publisher.objects.get(id=edit_id)
        return render(request, "app02/publisher/edit_publisher.html", {"publisher": publisher_obj})
    else:
        return HttpResponse("编辑的出版社不存在!")


def author_list(request):
    author_list = models.Author.objects.all()
    return render(request,'app02/author/author_list.html',context={"author_list": author_list})


def add_author(request):
    books = models.Book.objects.all()
    if request.method == 'POST':
        authorName = request.POST.get("author_name",'testAuthorName')
        # post提交的数据是多个值的时候一定会要用getlist,如多选的checkbox和多选的select
        books = request.POST.getlist("books")

        #以下是错误用法
        # author01 = models.Author()
        # author01.name = authorName
        author01 = models.Author.objects.create(name=authorName)
        author01.books.set(books)
        return redirect(to='app02:authorList')
    return render(request,'app02/author/add_author.html',context={"book_list": books})


def delete_author(request):
    authorId = request.GET.get('id')
    models.Author.objects.get(id=authorId).delete()
    return redirect(to='app02:authorList')


def edit_author(request):
    books = models.Book.objects.all()
    if request.method == 'POST':
        authorId = request.POST.get('author_id')
        authorName = request.POST.get("author_name", 'testAuthorName')
        # post提交的数据是多个值的时候一定会要用getlist,如多选的checkbox和多选的select
        books = request.POST.getlist("books")
        author = models.Author.objects.get(pk=authorId)
        author.name = authorName
        author.books.set(books)
        return redirect(to='app02:authorList')
    authorId = request.GET.get('id')
    author = models.Author.objects.get(id = authorId)
    return render(request,'app02/author/edit_author.html',context={'author': author,'book_list': books})

app02/templates/app02/author/add_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加作者</title>
</head>
<body>

<h1>添加作者</h1>

<form action="{% url 'app02:authorAdd' %}" method="post">
    <p>
       作者姓名:<input type="text" name="author_name">
    </p>

    <p>
        作品:
        <select multiple name="books">
            {% for book in book_list %}
            <option value="{{ book.id }}">{{ book.title }}</option>
            {% endfor %}
        </select>
    </p>

    <p>
        <input type="submit" value="提交">
    </p>

</form>

</body>
</html>

app02/templates/app02/author/author_list.html
{% extends "app03/dashboard.html" %}

{% block myMain %}
    <table border="1">
    <thead>
    <tr>
        <th>#</th>
        <th>ID</th>
        <th>名字</th>
        <th>作品</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for author in author_list %}
        <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ author.id }}</td>
        <td>{{ author.name }}</td>
        <td>
            {% for book in author.books.all %}
                {{ book.title }}&nbsp;
        {% endfor %}
        </td>
        <td>
            <a href="{% url 'app02:authorDelete' %}?id={{ author.id }}">删除</a>
            <a href="{% url 'app02:authorEdit' %}?id={{ author.id }}">编辑</a>
        </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}
<a href="{% url 'app02:authorAdd' %}">添加新的作者</a>

<h1>所有的作者</h1>

app02/templates/app02/author/edit_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑作者</title>
</head>
<body>

<h1>编辑作者</h1>

<form action="{% url 'app02:authorEdit' %}" method="post">
    <input type="text" name="author_id" value="{{ author.id }}" style="display: none">
    <p>
       作者姓名:<input type="text" name="author_name" value="{{ author.name }}">
    </p>

    <p>
        作品:
        <select multiple name="books">
            {% for book in book_list %}
{#                如果当前这本书 在 当前作者关联的所有书 里面 #}
                {% if book in author.books.all %}
                    <option selected value="{{ book.id }}">{{ book.title }}</option>
                {% else %}
                <option  value="{{ book.id }}">{{ book.title }}</option>
                {% endif %}
            {% endfor %}
        </select>
    </p>

    <p>
        <input type="submit" value="提交">
    </p>

</form>

</body>
</html>