app01/urls.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
# author:Administrator
# datetime:2020/1/4/004 9:26
# software: PyCharm

from django.contrib import admin
from django.urls import path,include,re_path
from . import views

app_name = 'myPerson'

urlpatterns = [
    # 查询 get
    path('', views.index, name='index'),
    path('getOne/<int:myPersonID>/', views.detail, name='detail'),
    # 新增 get + post
    path('add/', views.add, name='add'),
    # 删除 get
    path('delete/<int:myPersonID>/', views.delete, name='delete'),
    # 修改 get + post
    path('update/<int:myPersonID>/', views.update, name='update'),

]

app04/urls.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
# author:Administrator
# datetime:2020/1/4/004 9:26
# software: PyCharm

from django.contrib import admin
from django.urls import path,include,re_path
from django.views.generic import TemplateView

from . import views

app_name = 'app04'

urlpatterns = [
    # publisher
    path('', TemplateView.as_view(template_name="app04/bootstrapTable01.html"), name='app04'),
    path('table01/', TemplateView.as_view(template_name="app04/bootstrapTable01.html"), name='table01'),
    path('table02/', TemplateView.as_view(template_name="app04/bootstrapTable02.html"), name='table02'),
    path('getAllEmployees/', views.getAll,name='getAll'),

    path('delEmployee/', views.deletEmployee,name='deleteEmployee'),
]

myDjango00/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path,include,re_path
from django.conf import settings
from django.views import static
from django.conf.urls import url
from django.views.generic import TemplateView, RedirectView
from django.views.static import serve

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico')),
    # re_path(r'^media/(?P<path>.*)$', login_required(serve), kwargs={'document_root': settings.MEDIA_ROOT}),
    # re_path(r'^static/(?P<path>.*)$', login_required(serve), kwargs={'document_root': settings.STATIC_ROOT}, name='static'),
    # 注意login_required(serve)，日后需要权限控制
    re_path(r'^media/(?P<path>.*)$', static.serve, kwargs={'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', static.serve, kwargs={'document_root': settings.STATIC_ROOT},name='static'),
    # url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    # url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
    # path('media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
    # re_path('admin/|', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html")),
    path('admin/', admin.site.urls),
    path('app01/',include('app01.urls')),
    path('app02/',include('app02.urls')),
    path('app03/', include('app03.urls')),
    path('app04/', include('app04.urls')),
    path('app05/', include('app05.urls')),
    path('app06/', include('app06.urls')),

]

app04/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=60)
    age = models.IntegerField()
    address = models.TextField()

    def __str__(self):
        return self.name

    def employee2dict(employee):
        return {
            'id': employee.id,
            'name': employee.name,
            'age': employee.age,
            'address': employee.address
        }

app04/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
# Create your views here.
from app04 import models


def getAll(request):
    print(request.method)
    # 去数据库查出所有的出版社,填充到HTML中,给用户返回
    queryset = models.Employee.objects.all()
    responseData = []
    for employee in queryset:
        employeeJson = employee.employee2dict()
        responseData.append(employeeJson)
    print(responseData)
    return JsonResponse({"rows": responseData})


def deletEmployee(request):
    employeeID = request.GET.get("employeeID",0)
    models.Employee.objects.get(id=employeeID).delete()

    return JsonResponse(data={"deleteResult": "ok"})

app04/templates/app04/bootstrapTable01.html
{% extends "app04/dashboard.html" %}
{% block myCss %}
    <style>
        .like {
            margin-right: 10px;
        }
    </style>
{% endblock %}
{% block bootstrapTable01_css %} active{% endblock %}
{% block myMain %}
    {#    左上角工具栏#}
    <div id="toolbar">
        <button id="remove" class="btn btn-danger" disabled>
            <i class="glyphicon glyphicon-remove"></i> Delete
        </button>
        <button id="ssb" class="btn btn-primary">Submit</button>
    </div>
    {#    主表#}
    <table
            id="table"
            class="table table-striped"
            data-height="600"
            data-toolbar="#toolbar"
            data-show-button-icons="true"
            {#            data-show-button-text="true"#}
            data-search="true"
            data-search-on-enter-key="true"
            data-show-refresh="true"
            data-show-toggle="true"
            data-show-fullscreen="true"
            data-show-columns="true"
            data-show-columns-toggle-all="true"
            data-click-to-select="true"
            data-detail-view="true"
            data-detail-formatter="detailFormatter"
            data-minimum-count-columns="2"
            data-show-pagination-switch="true"
            data-pagination="true"
            data-id-field="id"
            data-sort-name="name"
            data-sort-order="desc"
            data-page-list="[10, 20, 50, all]"
            data-page-size="10"
            {#            data-show-footer="true"#}
            {#            默认为客户端分页#}
            {#            data-side-pagination="server"#}
            data-url="{% url 'app04:getAll' %}"
            {#            data-response-handler="responseHandler"#}
    >
    </table>

    <script>
        var $table = $('#table')
        var $remove = $('#remove')
        var selections = []
        $('#ssb').click(function () {
            alert(getIdSelections())
        })
        {#获取选中的行#}

        function getIdSelections() {
            return $.map($table.bootstrapTable('getSelections'), function (row) {
                return row.id
            })
        }

        {#处理返回的数据,相当于初始化#}

        {#function responseHandler(res) {#}
        {#    $.each(res.rows, function (i, row) {#}
        {#row.state = (parseInt(row.id)%2 == 1)#}
        {#        row.state = (row.id % 2 == 1)#}
        {#console.log($.inArray(row.id, selections) !== -1)#}
        {#console.log(row.id)#}
        {#console.log(parseInt(row.id)/2)#}
        {#    })#}
        {#    return res#}
        {#}#}

            {#详细信息的显示格式#}

            function detailFormatter(index, row) {
                var html = []
                $.each(row, function (key, value) {
                    html.push('<p><b>' + key + ':</b> ' + value + '</p>')
                })
                return html.join('')
            }

            {#操作列的显示格式#}

            function operateFormatter(value, row, index) {
                return [
                    '<a class="like" href="javascript:void(0)" title="Like">',
                    '<i class="fa fa-heart"></i>',
                    '</a>  ',
                    '<a class="remove" href="javascript:void(0)" title="Remove">',
                    '<i class="fa fa-trash"></i>',
                    '</a>'
                ].join('')
            }

            operateEvents001 = {
                'click .like': function (e, value, row, index) {
                    alert('You click like action, row: ' + JSON.stringify(row))
                },
                'click .remove': function (e, value, row, index) {

                    swal({
                            title: "Are you sure?",
                            text: "You will not be able to recover this imaginary file!",
                            type: "warning",
                            showCancelButton: true,
                            confirmButtonClass: "btn-danger",
                            confirmButtonText: "Yes, delete it!",
                            cancelButtonText: "No, cancel plx!",
                            closeOnConfirm: false,
                            closeOnCancel: false
                        },
                        function (isConfirm) {
                            if (isConfirm) {
                                $.ajax({
                                    url: "{% url 'app04:deleteEmployee'%}?employeeID=" + row.id,
                                    {#type:"DELETE",#}
                                    {#date:{"employeeID": row.id},#}
                                    {% comment %} beforeSend : function(){
                                     loadingIndex = layer.msg('处理中', {icon: 16});
                                     },{% endcomment %}
                                    success: function (result) {
                                        {#swal("result.deleteResult")#}
                                        {#alert(result.deleteResult);#}
                                        $table.bootstrapTable('remove', {
                                            field: 'id',
                                            values: [row.id]
                                        })
                                        swal("Deleted!", "Your imaginary file has been deleted.", "success");
                                    }
                                });

                            } else {
                                swal("Cancelled", "Your imaginary file is safe :)", "error");
                            }
                        });


                }
            }


            {#初始化bootstrapTable#}

            function initTable() {
                $table.bootstrapTable('destroy').bootstrapTable({
                    {#height: 550,#}
                    {#列设置#}
                    columns:
                        [{
                            field: 'state',
                            checkbox: true,
                            align: 'center',
                            valign: 'middle'
                        }, {
                            title: 'Item ID',
                            field: 'id',
                            align: 'center',
                            valign: 'middle',
                            sortable: true,
                        }, {
                            field: 'name',
                            title: 'Item Name',
                            sortable: true,
                            align: 'center'
                        }, {
                            field: 'age',
                            title: 'Item Age',
                            sortable: true,
                            align: 'center',
                        }, {
                            field: 'address',
                            title: 'Item Address',
                            sortable: true,
                            align: 'center',

                        }, {
                            field: 'operate',
                            title: 'Item Operate',
                            align: 'center',
                            clickToSelect: false,
                            events: operateEvents001,
                            formatter: operateFormatter
                        }]

                })
                {#功能未知#}
                $table.on('check.bs.table uncheck.bs.table ' +
                    'check-all.bs.table uncheck-all.bs.table',
                    function () {
                        $remove.prop('disabled', !$table.bootstrapTable('getSelections').length)

                        // save your data, here just save the current page
                        selections = getIdSelections()
                        // push or splice the selections if you want to save all data selections
                    })
                $table.on('all.bs.table', function (e, name, args) {
                    console.log(name, args)
                })

                $remove.click(function () {
                    var ids = getIdSelections()
                    $table.bootstrapTable('remove', {
                        field: 'id',
                        values: ids
                    })
                    $remove.prop('disabled', true)
                })
            }

            {#执行js#}
            $(function () {
                initTable()
            })
    </script>
{% endblock %}

app04/templates/app04/bootstrapTable02.html
{% extends "app04/dashboard.html" %}
{% block myCss %}
    <style>
        .like {
            margin-right: 10px;
        }
    </style>
{% endblock %}
{% block bootstrapTable02_css %}nav-link active{% endblock %}
{% block myMain %}
    {#    左上角工具栏#}
    <div id="toolbar">
        <button id="remove" class="btn btn-danger" disabled>
            <i class="glyphicon glyphicon-remove"></i> Delete
        </button>
        <button id="ssb" class="btn btn-primary">Submit</button>
    </div>
    {#    主表#}
    <table
            id="table"
            class="table table-striped"
            data-height="600"
            data-toolbar="#toolbar"
            data-show-button-icons="true"
{#            data-show-button-text="true"#}
            data-search="true"
            data-search-on-enter-key="true"
            data-show-refresh="true"
            data-show-toggle="true"
            data-show-fullscreen="true"
            data-show-columns="true"
            data-show-columns-toggle-all="true"
            data-click-to-select="true"
            data-detail-view="true"
            data-detail-formatter="detailFormatter"
            data-minimum-count-columns="2"
            data-show-pagination-switch="true"
            data-pagination="true"
            data-id-field="id"
            data-sort-name="name"
            data-sort-order="desc"
            data-page-list="[10, 20, 50, all]"
            data-page-size="20"
            {#            data-show-footer="true"#}
            {#            默认为客户端分页#}
            {#            data-side-pagination="server"#}
            data-url="{% url 'app04:getAll' %}"
{#            data-response-handler="responseHandler"#}
    >
    </table>

    <script>
        var $table = $('#table')
        var $remove = $('#remove')
        var selections = []
        $('#ssb').click(function () {
            alert(getIdSelections())
        })
        {#获取选中的行#}

        function getIdSelections() {
            return $.map($table.bootstrapTable('getSelections'), function (row) {
                return row.id
            })
        }

        {#处理返回的数据,相当于初始化#}

        {#function responseHandler(res) {#}
        {#    $.each(res.rows, function (i, row) {#}
                {#row.state = (parseInt(row.id)%2 == 1)#}
        {#        row.state = (row.id % 2 == 1)#}
                {#console.log($.inArray(row.id, selections) !== -1)#}
                {#console.log(row.id)#}
                {#console.log(parseInt(row.id)/2)#}
        {#    })#}
        {#    return res#}
        {#}#}

        {#详细信息的显示格式#}

        function detailFormatter(index, row) {
            var html = []
            $.each(row, function (key, value) {
                html.push('<p><b>' + key + ':</b> ' + value + '</p>')
            })
            return html.join('')
        }

        {#操作列的显示格式#}

        function operateFormatter(value, row, index) {
            return [
                '<a class="like" href="javascript:void(0)" title="Like">',
                '<i class="fa fa-heart"></i>',
                '</a>  ',
                '<a class="remove" href="javascript:void(0)" title="Remove">',
                '<i class="fa fa-trash"></i>',
                '</a>'
            ].join('')
        }

        window.operateEvents = {
            'click .like': function (e, value, row, index) {
                alert('You click like action, row: ' + JSON.stringify(row))
            },
            'click .remove': function (e, value, row, index) {
                $table.bootstrapTable('remove', {
                    field: 'id',
                    values: [row.id]
                })
            }
        }


        {#初始化bootstrapTable#}

        function initTable() {
            $table.bootstrapTable('destroy').bootstrapTable({
                {#height: 550,#}
                {#列设置#}
                columns:
                    [{
                        field: 'state',
                        checkbox: true,
                        align: 'center',
                        valign: 'middle'
                    }, {
                        title: 'Item ID',
                        field: 'id',
                        align: 'center',
                        valign: 'middle',
                        sortable: true,
                    }, {
                        field: 'name',
                        title: 'Item Name',
                        sortable: true,
                        align: 'center'
                    }, {
                        field: 'age',
                        title: 'Item Age',
                        sortable: true,
                        align: 'center',
                    }, {
                        field: 'address',
                        title: 'Item Address',
                        sortable: true,
                        align: 'center',

                    }, {
                        field: 'operate',
                        title: 'Item Operate',
                        align: 'center',
                        clickToSelect: false,
                        events: window.operateEvents,
                        formatter: operateFormatter
                    }]

            })
            {#功能未知#}
            $table.on('check.bs.table uncheck.bs.table ' +
                'check-all.bs.table uncheck-all.bs.table',
                function () {
                    $remove.prop('disabled', !$table.bootstrapTable('getSelections').length)

                    // save your data, here just save the current page
                    selections = getIdSelections()
                    // push or splice the selections if you want to save all data selections
                })
            $table.on('all.bs.table', function (e, name, args) {
                console.log(name, args)
            })

            $remove.click(function () {
                var ids = getIdSelections()
                $table.bootstrapTable('remove', {
                    field: 'id',
                    values: ids
                })
                $remove.prop('disabled', true)
            })
        }

        {#执行js#}
        $(function () {
            initTable()
        })
    </script>
{% endblock %}

app04/templates/app04/clientView.html
{% extends "app04/dashboard.html" %}
{% block myCss %}
    <style>
        .like {
            margin-right: 10px;
        }
    </style>
{% endblock %}
{% block bootstrapTable01_css %} active{% endblock %}
{% block myMain %}

{% endblock %}

app04/templates/app04/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>Dashboard Template for Bootstrap</title>
    <link href="{% static "bootstrap4.3.1/dashboard.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'bootstrap4.3.1/css/bootstrap.min.css ' %}">
    <link rel="stylesheet" href="{% static "bootstraptable1.15.5/bootstrap-table.min.css" %}">
    <link rel="stylesheet" href="{% static 'Font-Awesome-5.6.3/css/all.css ' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css ' %}">
    {#    <!-- Custom styles for this template -->#}

    {##}
    {#    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->#}
    <script src="{% static "jquery/jquery-3.4.1.min.js" %}" type="text/javascript"></script>
    <script src="{% static "popper.js-1.16.0/umd/popper.min.js" %}"></script>
    {#    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->#}
    <script src="{% static "bootstrap4.3.1/js/bootstrap.min.js" %}"></script>
    <script src="{% static "bootstraptable1.15.5/bootstrap-table.min.js" %}"></script>
    <script src="{% static "sweetalert/sweetalert.min.js" %}"></script>


    {% comment %}每个页面预留的自定义css{% endcomment %}
    {% block myCss %}{% endblock %}

</head>

<body>

<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="#">Sign out</a>
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="home"></span>Dashboard <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block bootstrapTable01_css %}{% endblock %}" href="{% url 'app04:table01' %}">
                            <span data-feather="file"></span>BootstrapTable01
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block bootstrapTable02_css %}{% endblock %}" href="{% url 'app04:table02' %}">
                            <i class="fa fa-bomb" aria-hidden="true"></i>BootstrapTable02
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="users"></span>Customers
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="bar-chart-2"></span>
                            Reports
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="layers"></span>
                            Integrations
                        </a>
                    </li>
                </ul>


            </div>
        </nav>


        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            {% block myMain %}
                <h1>Hello DashBoard</h1>
            {% endblock %}
        </main>

    </div>
</div>

</body>
</html>