app01/urls.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
# author:Administrator
# datetime:2020/1/4/004 9:26
# software: PyCharm

from django.contrib import admin
from django.urls import path,include,re_path
from . import views

app_name = 'myPerson'

urlpatterns = [
    # 查询 get
    path('', views.index, name='index'),
    path('getOne/<int:myPersonID>/', views.detail, name='detail'),
    # 新增 get + post
    path('add/', views.add, name='add'),
    # 删除 get
    path('delete/<int:myPersonID>/', views.delete, name='delete'),
    # 修改 get + post
    path('update/<int:myPersonID>/', views.update, name='update'),

]

myDjango00/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path,include,re_path
from django.conf import settings
from django.views import static
from django.conf.urls import url
from django.views.generic import TemplateView, RedirectView
from django.views.static import serve

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico')),
    # re_path(r'^media/(?P<path>.*)$', login_required(serve), kwargs={'document_root': settings.MEDIA_ROOT}),
    # re_path(r'^static/(?P<path>.*)$', login_required(serve), kwargs={'document_root': settings.STATIC_ROOT}, name='static'),
    # 注意login_required(serve)，日后需要权限控制
    re_path(r'^media/(?P<path>.*)$', static.serve, kwargs={'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', static.serve, kwargs={'document_root': settings.STATIC_ROOT},name='static'),
    # url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    # url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
    # path('media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
    # re_path('admin/|', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html")),
    path('admin/', admin.site.urls),
    path('app01/',include('app01.urls')),
    path('app02/',include('app02.urls')),
    path('app03/', include('app03.urls')),
    path('app04/', include('app04.urls')),
    path('app05/', include('app05.urls')),
    path('app06/', include('app06.urls')),

]

app01/models.py
from django.db import models

import uuid,time, random, string

from django.db import models


def image_upload_to(instance, filename):
    today = time.strftime("%F")
    ran_str = ''.join(random.sample(string.ascii_letters + string.digits, 8))
    newKey = filename[-20:]
    filename01 = today + "---" + ran_str + "---" + newKey#2011-01-02---2sdxaega---asdfasdfasdfasdfasd.jpg
    return 'weixinFiles/{filename}'.format(filename=filename01)

# Create your models here.
class MyPerson(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField(max_length=200)
    image = models.ImageField(upload_to=image_upload_to)

    def __str__(self):
        return self.name

app01/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import MyPerson
import time, logging, os
# Create your views here.

def index(request):
    latest_Person_list = MyPerson.objects.all()[:10]
    myPersonList = {'latest_person_list': latest_Person_list}
    return render(request, 'app01/myPersonList.html', myPersonList)

def detail(request, myPersonID):
    # print( myPersonID)
    myperson = get_object_or_404(MyPerson, pk=myPersonID)
    # question.cho
    return render(request, 'app01/myPersonDetail.html', {'myPerson01': myperson})

#通过模型进行文件上传
def add(request):
    if(request.method == 'POST'):
        #这是文件别名
        filename=request.POST.get("fileName",default='myFN')
        files = request.FILES
        for key, uploaded_file in files.items():
            myPerson = MyPerson()
            myPerson.name = filename
            myPerson.image = uploaded_file
            myPerson.save()
        return redirect("myPerson:index")
    return render(request, 'app01/myPersonAdd.html')

#最简单版本的文件上传
# 处理上传文件的函数
# def add(request):
#     """
#     保存上传文件前，数据需要存放在某个位置。默认当上传文件小于2.5M时，django会将上传文件的全部内容读进内存。从内存读取一次，写磁盘一次。
#     但当上传文件很大时，django会把上传文件写到临时文件中，然后存放到系统临时文件夹中。
#     :param request:
#     :return:
#     """
#     if request.method == "POST":
#         print(request.FILES)
#         #真正的文件名称
#         print(request.FILES["file00"].name)
#         # 从请求的FILES中获取上传文件的文件名，file为页面上type=files类型input的name属性值
#         filename = request.FILES["file00"].name
#         newFilePah = "myUpload/"+filename
#         # # 在项目目录下新建一个文件
#         with open(newFilePah, "wb") as f:
#             # 从上传的文件对象中一点一点读
#             for i in request.FILES["file00"].chunks():
#                 # 写入本地文件
#                 f.write(i)
#         return HttpResponse("上传OK")
#
#     else:
#         return render(request, 'app01/myPersonAdd.html')


def delete(request,myPersonID):
    myPerson = MyPerson.objects.get(id=myPersonID)
    if (myPersonID):
        myPerson.delete()
        return redirect("myPerson:index")
    return HttpResponse("无法删除！！！！")


def update(request, myPersonID):
    print("sadfasdfasdfasdfasdf")
    myPerson = MyPerson.objects.get(id=myPersonID)
    if (request.method == 'POST'):
        filename = request.POST.get("fileName", default='myFN')
        file = request.FILES.get("file00")
        if(file):
            myPerson.image = file
        myPerson.name = filename
        myPerson.save()
        #此时是否需要reverse()???
        return redirect("myPerson:index")
    return render(request, 'app01/myPersonUpdate.html',{"myPerson": myPerson})

app01/templates/app01/index.html
<!DOCTYPE html>
<html lang="zh-CN">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Bootstrap 101 Template</title>
    <script src="{% static "bootstrap3.3.7/js/bootstrap.min.js" %}"></script>
    <link href="{% static "bootstrap3.3.7/css/bootstrap.min.css " %}" rel="stylesheet">
  </head>
  <body>
    <h2>Welcom to Bootstrap3.3.7!!!!!</h2>


<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="{% static "jquery/jquery-3.4.1.min.js" %}" type="text/javascript"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="{% static "bootstrap3.3.7/js/bootstrap.min.js" %}"></script>
  </body>
</html>

app01/templates/app01/myPersonAdd.html
{% load static %}
<script src="{% static "jquery/jquery-3.4.1.min.js" %}" type="text/javascript"></script>
<script src="{% static "app01/jquery/jquery-3.4.1.min.js" %}" type="text/javascript"></script>

<form action="{% url 'myPerson:add' %}" enctype="multipart/form-data" method="post">
    name:<input type="text" id="myName" name="fileName"/>
    image:<input  type="file" id="imgPath" name="file00" />
    <button type="submit">Sub</button>
</form>

app01/templates/app01/myPersonDetail.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<h1>{{ myPerson01.name }}</h1>

<br/>

<img src="{{ myPerson01.image.url}}" height=100 width=100 />



<br/>
<a href="{% url 'myPerson:index' %}">Go Back to myPerson Idex</a>

app01/templates/app01/myPersonList.html
<!DOCTYPE html>
<html lang="zh-CN">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Bootstrap 101 Template</title>
    <script src="{% static "bootstrap3.3.7/js/bootstrap.min.js" %}"></script>
    <link href="{% static "bootstrap3.3.7/css/bootstrap.min.css " %}" rel="stylesheet">
  </head>
  <body>
    <h2>MyPerson列表</h2>

</br>
{% if latest_person_list %}
    <table border="1">
        <thead>
            <tr>
                <td>序号</td>
                <td>姓名</td>
                <td>image</td>
                <td>操作</td>
            </tr>
        </thead>
        {% for myPerson in latest_person_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ myPerson.name}}</td>
            <td>
                {% if myPerson.image.url != '' %}
                    <img src="{{ myPerson.image.url}}" height=100 width=100 alt=""/>
                {%  endif %}
            </td>
            <td>
                <a href="{% url 'myPerson:detail' myPerson.id %}">查看</a>
                <a href="{% url 'myPerson:update' myPerson.id %}">修改</a>
                <a href="{% url 'myPerson:delete' myPerson.id %}">删除</a>
            </td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No MyPerson are available.</p>
{% endif %}

<br/>
<a href="{% url 'myPerson:add'%}">新增myPerson</a>

<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="{% static "jquery/jquery-3.4.1.min.js" %}" type="text/javascript"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="{% static "bootstrap3.3.7/js/bootstrap.min.js" %}"></script>
  </body>
</html>

app01/templates/app01/myPersonUpdate.html
{% load static %}
<script src="{% static "jquery/jquery-3.4.1.min.js" %}" type="text/javascript"></script>
<script src="{% static "app01/jquery/jquery-3.4.1.min.js" %}" type="text/javascript"></script>

<form action="{% url 'myPerson:update'  myPerson.id %}" enctype="multipart/form-data" method="post">
    name:<input type="text" id="myName" name="fileName" value="{{ myPerson.name }}"/>
    image:<img src="{{ myPerson.image.url}}" height=100 width=100 alt=""/>
    newImage:<input  type="file" id="imgPath" name="file00" />
    <button type="submit">Sub</button>
</form>